// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App represents the Wails application with bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteTool removes a CLI tool binary from the tools directory.
 */
export function DeleteTool(name: string): $CancellablePromise<void> {
    return $Call.ByID(2696011852, name);
}

/**
 * ExecuteTool runs a CLI tool with the given parameters and streams output.
 */
export function ExecuteTool(name: string, params: { [_ in string]?: any }): $CancellablePromise<$models.ExecuteResult | null> {
    return $Call.ByID(3793969274, name, params).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetSchema returns the JSON Schema for a tool.
 */
export function GetSchema(name: string): $CancellablePromise<$models.ToolSchema | null> {
    return $Call.ByID(2867622096, name).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetSettings returns the current application settings.
 */
export function GetSettings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(2554697378).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ImportTool copies a CLI binary from sourcePath into the tools directory.
 */
export function ImportTool(sourcePath: string): $CancellablePromise<void> {
    return $Call.ByID(1277206998, sourcePath);
}

/**
 * ListTools scans and returns all available CLI tools.
 */
export function ListTools(): $CancellablePromise<$models.ToolInfo[]> {
    return $Call.ByID(3282129816).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * RefreshTools forces a rescan of the tools directory.
 */
export function RefreshTools(): $CancellablePromise<void> {
    return $Call.ByID(115815919);
}

/**
 * UpdateSettings persists new application settings and creates cli dir if needed.
 */
export function UpdateSettings(newSettings: $models.AppSettings): $CancellablePromise<void> {
    return $Call.ByID(2894041249, newSettings);
}

// Private type creation functions
const $$createType0 = $models.ExecuteResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ToolSchema.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.AppSettings.createFrom;
const $$createType5 = $models.ToolInfo.createFrom;
const $$createType6 = $Create.Array($$createType5);
