// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App represents the Wails application with bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ExecuteTool runs a CLI tool with the given parameters and streams output.
 */
export function ExecuteTool(name: string, params: { [_ in string]?: any }): $CancellablePromise<$models.ExecuteResult | null> {
    return $Call.ByID(3793969274, name, params).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetSchema returns the JSON Schema for a tool.
 */
export function GetSchema(name: string): $CancellablePromise<$models.ToolSchema | null> {
    return $Call.ByID(2867622096, name).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * ListTools scans and returns all available CLI tools.
 */
export function ListTools(): $CancellablePromise<$models.ToolInfo[]> {
    return $Call.ByID(3282129816).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ExecuteResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ToolSchema.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.ToolInfo.createFrom;
const $$createType5 = $Create.Array($$createType4);
