// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App represents the Wails application with bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteTool removes a CLI tool binary from the tools directory.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTool(name) {
    return $Call.ByID(2696011852, name);
}

/**
 * ExecuteTool runs a CLI tool with the given parameters and streams output.
 * @param {string} name
 * @param {{ [_ in string]?: any }} params
 * @returns {$CancellablePromise<$models.ExecuteResult | null>}
 */
export function ExecuteTool(name, params) {
    return $Call.ByID(3793969274, name, params).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetSchema returns the JSON Schema for a tool.
 * @param {string} name
 * @returns {$CancellablePromise<$models.ToolSchema | null>}
 */
export function GetSchema(name) {
    return $Call.ByID(2867622096, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetSettings returns the current application settings.
 * @returns {$CancellablePromise<$models.AppSettings>}
 */
export function GetSettings() {
    return $Call.ByID(2554697378).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ImportTool copies a CLI binary from sourcePath into the tools directory.
 * @param {string} sourcePath
 * @returns {$CancellablePromise<void>}
 */
export function ImportTool(sourcePath) {
    return $Call.ByID(1277206998, sourcePath);
}

/**
 * ListTools scans and returns all available CLI tools.
 * @returns {$CancellablePromise<$models.ToolInfo[]>}
 */
export function ListTools() {
    return $Call.ByID(3282129816).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * RefreshTools forces a rescan of the tools directory.
 * @returns {$CancellablePromise<void>}
 */
export function RefreshTools() {
    return $Call.ByID(115815919);
}

/**
 * UpdateSettings persists new application settings and creates cli dir if needed.
 * @param {$models.AppSettings} newSettings
 * @returns {$CancellablePromise<void>}
 */
export function UpdateSettings(newSettings) {
    return $Call.ByID(2894041249, newSettings);
}

// Private type creation functions
const $$createType0 = $models.ExecuteResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ToolSchema.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.AppSettings.createFrom;
const $$createType5 = $models.ToolInfo.createFrom;
const $$createType6 = $Create.Array($$createType5);
