// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppSettings holds user-configurable application settings persisted in db/settings.json.
 */
export class AppSettings {
    /**
     * Creates a new AppSettings instance.
     * @param {Partial<AppSettings>} [$$source = {}] - The source object to create the AppSettings.
     */
    constructor($$source = {}) {
        if (!("cliPath" in $$source)) {
            /**
             * path to directory containing CLI tools
             * @member
             * @type {string}
             */
            this["cliPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings(/** @type {Partial<AppSettings>} */($$parsedSource));
    }
}

/**
 * ExecuteResult is the summary returned after execution completes.
 */
export class ExecuteResult {
    /**
     * Creates a new ExecuteResult instance.
     * @param {Partial<ExecuteResult>} [$$source = {}] - The source object to create the ExecuteResult.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("output" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["output"] = "";
        }
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["code"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExecuteResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExecuteResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExecuteResult(/** @type {Partial<ExecuteResult>} */($$parsedSource));
    }
}

/**
 * SchemaProp describes a single parameter.
 */
export class SchemaProp {
    /**
     * Creates a new SchemaProp instance.
     * @param {Partial<SchemaProp>} [$$source = {}] - The source object to create the SchemaProp.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["descriptionZh"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {any | undefined}
             */
            this["default"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["enum"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["format"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["minimum"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["maximum"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{"type": string} | null | undefined}
             */
            this["items"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SchemaProp instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SchemaProp}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("enum" in $$parsedSource) {
            $$parsedSource["enum"] = $$createField4_0($$parsedSource["enum"]);
        }
        return new SchemaProp(/** @type {Partial<SchemaProp>} */($$parsedSource));
    }
}

/**
 * StepGroup defines a group of fields for multi-step forms.
 */
export class StepGroup {
    /**
     * Creates a new StepGroup instance.
     * @param {Partial<StepGroup>} [$$source = {}] - The source object to create the StepGroup.
     */
    constructor($$source = {}) {
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["titleZh"] = undefined;
        }
        if (!("fields" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["fields"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StepGroup instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StepGroup}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField2_0($$parsedSource["fields"]);
        }
        return new StepGroup(/** @type {Partial<StepGroup>} */($$parsedSource));
    }
}

/**
 * ToolInfo represents a discovered CLI tool.
 */
export class ToolInfo {
    /**
     * Creates a new ToolInfo instance.
     * @param {Partial<ToolInfo>} [$$source = {}] - The source object to create the ToolInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["descriptionZh"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["longDescription"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["longDescriptionZh"] = undefined;
        }
        if (!("ready" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ready"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ToolInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolInfo(/** @type {Partial<ToolInfo>} */($$parsedSource));
    }
}

/**
 * ToolSchema represents the parsed --schema output of a CLI tool.
 */
export class ToolSchema {
    /**
     * Creates a new ToolSchema instance.
     * @param {Partial<ToolSchema>} [$$source = {}] - The source object to create the ToolSchema.
     */
    constructor($$source = {}) {
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["titleZh"] = undefined;
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["descriptionZh"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["longDescription"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["longDescriptionZh"] = undefined;
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("properties" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: SchemaProp }}
             */
            this["properties"] = {};
        }
        if (!("required" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["required"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {StepGroup[] | undefined}
             */
            this["x-steps"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolSchema instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ToolSchema}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType2;
        const $$createField8_0 = $$createType0;
        const $$createField9_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("properties" in $$parsedSource) {
            $$parsedSource["properties"] = $$createField7_0($$parsedSource["properties"]);
        }
        if ("required" in $$parsedSource) {
            $$parsedSource["required"] = $$createField8_0($$parsedSource["required"]);
        }
        if ("x-steps" in $$parsedSource) {
            $$parsedSource["x-steps"] = $$createField9_0($$parsedSource["x-steps"]);
        }
        return new ToolSchema(/** @type {Partial<ToolSchema>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = SchemaProp.createFrom;
const $$createType2 = $Create.Map($Create.Any, $$createType1);
const $$createType3 = StepGroup.createFrom;
const $$createType4 = $Create.Array($$createType3);
