// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ExecuteResult is the summary returned after execution completes.
 */
export class ExecuteResult {
    "status": string;
    "output": string;
    "code": number;

    /** Creates a new ExecuteResult instance. */
    constructor($$source: Partial<ExecuteResult> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("output" in $$source)) {
            this["output"] = "";
        }
        if (!("code" in $$source)) {
            this["code"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExecuteResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ExecuteResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExecuteResult($$parsedSource as Partial<ExecuteResult>);
    }
}

/**
 * SchemaProp describes a single parameter.
 */
export class SchemaProp {
    "type": string;
    "description": string;
    "default"?: any;
    "enum"?: string[];
    "format"?: string;
    "minimum"?: number | null;
    "maximum"?: number | null;
    "items"?: {"type": string} | null;

    /** Creates a new SchemaProp instance. */
    constructor($$source: Partial<SchemaProp> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SchemaProp instance from a string or object.
     */
    static createFrom($$source: any = {}): SchemaProp {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("enum" in $$parsedSource) {
            $$parsedSource["enum"] = $$createField3_0($$parsedSource["enum"]);
        }
        return new SchemaProp($$parsedSource as Partial<SchemaProp>);
    }
}

/**
 * StepGroup defines a group of fields for multi-step forms.
 */
export class StepGroup {
    "title": string;
    "fields": string[];

    /** Creates a new StepGroup instance. */
    constructor($$source: Partial<StepGroup> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("fields" in $$source)) {
            this["fields"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StepGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): StepGroup {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField1_0($$parsedSource["fields"]);
        }
        return new StepGroup($$parsedSource as Partial<StepGroup>);
    }
}

/**
 * ToolInfo represents a discovered CLI tool.
 */
export class ToolInfo {
    "name": string;
    "version": string;
    "description": string;
    "ready": boolean;
    "error"?: string;

    /** Creates a new ToolInfo instance. */
    constructor($$source: Partial<ToolInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("ready" in $$source)) {
            this["ready"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolInfo($$parsedSource as Partial<ToolInfo>);
    }
}

/**
 * ToolSchema represents the parsed --schema output of a CLI tool.
 */
export class ToolSchema {
    "title": string;
    "description": string;
    "type": string;
    "properties": { [_ in string]?: SchemaProp };
    "required": string[];
    "x-steps"?: StepGroup[];

    /** Creates a new ToolSchema instance. */
    constructor($$source: Partial<ToolSchema> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("properties" in $$source)) {
            this["properties"] = {};
        }
        if (!("required" in $$source)) {
            this["required"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolSchema instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolSchema {
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("properties" in $$parsedSource) {
            $$parsedSource["properties"] = $$createField3_0($$parsedSource["properties"]);
        }
        if ("required" in $$parsedSource) {
            $$parsedSource["required"] = $$createField4_0($$parsedSource["required"]);
        }
        if ("x-steps" in $$parsedSource) {
            $$parsedSource["x-steps"] = $$createField5_0($$parsedSource["x-steps"]);
        }
        return new ToolSchema($$parsedSource as Partial<ToolSchema>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = SchemaProp.createFrom;
const $$createType2 = $Create.Map($Create.Any, $$createType1);
const $$createType3 = StepGroup.createFrom;
const $$createType4 = $Create.Array($$createType3);
